"use client";

import { Button } from "@base-ui/react/button";
import { Input } from "@base-ui/react/input";
import { NumberField } from "@base-ui/react/number-field";
import { Select } from "@base-ui/react/select";
import { useDeferredValue, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import type { DashboardData, TrendExplorerRecord } from "@/lib/types";

type DashboardShellProps = {
  initialData: DashboardData;
};

const SOURCE_FILTER_OPTIONS = [
  { label: "All sources", value: "all" },
  { label: "Reddit", value: "reddit" },
  { label: "Hacker News", value: "hacker_news" },
  { label: "GitHub", value: "github" },
  { label: "Wikipedia", value: "wikipedia" },
] as const;

const SORT_OPTIONS = [
  { label: "Rank", value: "rank" },
  { label: "Score", value: "score" },
  { label: "Biggest mover", value: "mover" },
  { label: "Newest", value: "newest" },
] as const;

export function DashboardShell({ initialData }: DashboardShellProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [keyword, setKeyword] = useState("");
  const [selectedSource, setSelectedSource] = useState<string>("all");
  const [minimumScore, setMinimumScore] = useState<number | null>(0);
  const [sortBy, setSortBy] = useState<string>("rank");
  const [refreshError, setRefreshError] = useState<string | null>(null);
  const deferredKeyword = useDeferredValue(keyword);

  const filteredTrends = useMemo(() => {
    const normalizedKeyword = deferredKeyword.trim().toLowerCase();
    const minimum = minimumScore ?? 0;
    const trends = initialData.explorer.trends.filter((trend) => {
      const matchesSource =
        selectedSource === "all" || trend.sources.includes(selectedSource);
      const matchesKeyword =
        normalizedKeyword.length === 0 ||
        trend.name.toLowerCase().includes(normalizedKeyword) ||
        trend.evidencePreview.some((item) => item.toLowerCase().includes(normalizedKeyword));
      const matchesScore = trend.score.total >= minimum;
      return matchesSource && matchesKeyword && matchesScore;
    });

    return [...trends].sort((left, right) => {
      if (sortBy === "score") {
        return right.score.total - left.score.total || left.rank - right.rank;
      }
      if (sortBy === "mover") {
        return (right.rankChange ?? Number.NEGATIVE_INFINITY) - (left.rankChange ?? Number.NEGATIVE_INFINITY) || left.rank - right.rank;
      }
      if (sortBy === "newest") {
        return compareDates(right.firstSeenAt, left.firstSeenAt) || left.rank - right.rank;
      }
      return left.rank - right.rank;
    });
  }, [deferredKeyword, initialData.explorer.trends, minimumScore, selectedSource, sortBy]);

  const biggestMover = useMemo(() => {
    return initialData.explorer.trends.reduce<TrendExplorerRecord | null>((current, trend) => {
      if (current === null) {
        return trend;
      }
      return (trend.rankChange ?? Number.NEGATIVE_INFINITY) > (current.rankChange ?? Number.NEGATIVE_INFINITY)
        ? trend
        : current;
    }, null);
  }, [initialData.explorer.trends]);

  function handleRefresh() {
    setRefreshError(null);
    startTransition(async () => {
      const response = await fetch("/api/refresh", { method: "POST" });
      if (!response.ok) {
        const payload = (await response.json()) as { error?: string };
        setRefreshError(payload.error ?? "Refresh failed");
        return;
      }
      router.refresh();
    });
  }

  return (
    <main className="dashboard-page">
      <section className="hero-panel">
        <div>
          <p className="eyebrow">Trend Friend</p>
          <h1>Trend explorer with movement, coverage, and score depth.</h1>
          <p className="hero-copy">
            The dashboard now reads a richer V2 export generated by the Python pipeline, so the
            browser can show rank movement and larger result sets without deriving business logic.
          </p>
        </div>
        <div className="hero-meta">
          <div className="stat-card">
            <span>Explorer snapshot</span>
            <strong>{formatTimestamp(initialData.explorer.generatedAt)}</strong>
          </div>
          <div className="stat-card">
            <span>Tracked trends</span>
            <strong>{initialData.explorer.trends.length}</strong>
          </div>
          <div className="stat-card">
            <span>Biggest mover</span>
            <strong>{biggestMover?.name ?? "No data"}</strong>
          </div>
          <Button className="refresh-button" disabled={isPending} onClick={handleRefresh}>
            {isPending ? "Refreshing..." : "Refresh trends"}
          </Button>
        </div>
      </section>

      <section className="filters-panel filters-panel-wide">
        <label className="filter-field">
          <span>Keyword</span>
          <Input
            className="text-input"
            placeholder="AI agents, robotics, battery..."
            value={keyword}
            onChange={(event) => setKeyword(event.target.value)}
          />
        </label>

        <label className="filter-field">
          <span>Source</span>
          <Select.Root value={selectedSource} onValueChange={(value) => setSelectedSource(value ?? "all")}>
            <Select.Trigger className="select-trigger">
              <Select.Value />
              <Select.Icon className="select-icon">+</Select.Icon>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner className="select-positioner" sideOffset={8}>
                <Select.Popup className="select-popup">
                  <Select.List className="select-list">
                    {SOURCE_FILTER_OPTIONS.map((option) => (
                      <Select.Item className="select-item" key={option.value} value={option.value}>
                        <Select.ItemText>{option.label}</Select.ItemText>
                      </Select.Item>
                    ))}
                  </Select.List>
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        </label>

        <label className="filter-field">
          <span>Sort</span>
          <Select.Root value={sortBy} onValueChange={(value) => setSortBy(value ?? "rank")}>
            <Select.Trigger className="select-trigger">
              <Select.Value />
              <Select.Icon className="select-icon">+</Select.Icon>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner className="select-positioner" sideOffset={8}>
                <Select.Popup className="select-popup">
                  <Select.List className="select-list">
                    {SORT_OPTIONS.map((option) => (
                      <Select.Item className="select-item" key={option.value} value={option.value}>
                        <Select.ItemText>{option.label}</Select.ItemText>
                      </Select.Item>
                    ))}
                  </Select.List>
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        </label>

        <label className="filter-field">
          <span>Minimum score</span>
          <NumberField.Root
            className="number-field"
            min={0}
            value={minimumScore}
            onValueChange={setMinimumScore}
          >
            <NumberField.Group className="number-group">
              <NumberField.Decrement className="number-button">-</NumberField.Decrement>
              <NumberField.Input className="number-input" />
              <NumberField.Increment className="number-button">+</NumberField.Increment>
            </NumberField.Group>
          </NumberField.Root>
        </label>
      </section>

      {refreshError ? <p className="error-banner">{refreshError}</p> : null}

      <section className="content-grid">
        <div className="ranking-panel">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Explorer</p>
              <h2>{filteredTrends.length} trends match the current filters</h2>
            </div>
          </div>

          {filteredTrends.length === 0 ? (
            <div className="empty-state">
              <h3>No trends match these filters.</h3>
              <p>Lower the minimum score or broaden the keyword and source filters.</p>
            </div>
          ) : (
            <div className="explorer-table-wrap">
              <table className="explorer-table">
                <thead>
                  <tr>
                    <th>Trend</th>
                    <th>Rank</th>
                    <th>Movement</th>
                    <th>Total</th>
                    <th>Signals</th>
                    <th>Sources</th>
                    <th>Evidence</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredTrends.map((trend) => (
                    <tr key={trend.id}>
                      <td>
                        <div className="trend-cell">
                          <strong>{trend.name}</strong>
                          <span>
                            First seen {trend.firstSeenAt ? formatDateOnly(trend.firstSeenAt) : "this run"}
                          </span>
                        </div>
                      </td>
                      <td>
                        <strong>#{trend.rank}</strong>
                      </td>
                      <td>
                        <span className={movementClassName(trend.rankChange)}>
                          {formatRankChange(trend.rankChange)}
                        </span>
                        <small>{formatMomentum(trend.momentum.percentDelta)}</small>
                      </td>
                      <td>
                        <div className="score-cell">
                          <strong>{trend.score.total.toFixed(1)}</strong>
                          <span>
                            S {trend.score.social.toFixed(1)} / D {trend.score.developer.toFixed(1)} / K{" "}
                            {trend.score.knowledge.toFixed(1)}
                          </span>
                        </div>
                      </td>
                      <td>{trend.coverage.signalCount}</td>
                      <td>
                        <div className="source-row source-row-compact">
                          {trend.sources.map((source) => (
                            <span className="source-badge" key={source}>
                              {formatSourceLabel(source)}
                            </span>
                          ))}
                        </div>
                      </td>
                      <td className="evidence-cell">{trend.evidencePreview[0] ?? "No evidence available."}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        <aside className="history-panel">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Recent runs</p>
              <h2>Snapshot history</h2>
            </div>
          </div>

          <div className="snapshot-list">
            {initialData.history.snapshots.map((snapshot) => (
              <section className="snapshot-card" key={snapshot.capturedAt}>
                <header>
                  <strong>{formatTimestamp(snapshot.capturedAt)}</strong>
                  <span>{snapshot.trends.length} stored ranks</span>
                </header>
                <ol>
                  {snapshot.trends.slice(0, 3).map((trend) => (
                    <li key={trend.id}>
                      <span>{trend.name}</span>
                      <strong>{trend.score.total.toFixed(1)}</strong>
                    </li>
                  ))}
                </ol>
              </section>
            ))}
          </div>
        </aside>
      </section>
    </main>
  );
}

function formatTimestamp(value: string) {
  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function formatDateOnly(value: string) {
  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
  }).format(new Date(value));
}

function formatSourceLabel(source: string) {
  return source
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function formatRankChange(value: number | null | undefined) {
  if (value == null) {
    return "New";
  }
  if (value > 0) {
    return `+${value}`;
  }
  if (value < 0) {
    return `${value}`;
  }
  return "0";
}

function formatMomentum(value: number | null | undefined) {
  if (value == null) {
    return "No prior run";
  }
  return `${value > 0 ? "+" : ""}${value.toFixed(1)}%`;
}

function movementClassName(rankChange: number | null | undefined) {
  if (rankChange == null) {
    return "movement-pill movement-pill-new";
  }
  if (rankChange > 0) {
    return "movement-pill movement-pill-up";
  }
  if (rankChange < 0) {
    return "movement-pill movement-pill-down";
  }
  return "movement-pill";
}

function compareDates(left: string | null, right: string | null) {
  if (left === null && right === null) {
    return 0;
  }
  if (left === null) {
    return -1;
  }
  if (right === null) {
    return 1;
  }
  return new Date(left).getTime() - new Date(right).getTime();
}
