"use client";

import { Button } from "@base-ui/react/button";
import { Input } from "@base-ui/react/input";
import { NumberField } from "@base-ui/react/number-field";
import { Select } from "@base-ui/react/select";
import Link from "next/link";
import { useDeferredValue, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import type { DashboardData } from "@/lib/types";

type DashboardShellProps = {
  initialData: DashboardData;
};

const SOURCE_FILTER_OPTIONS = [
  { label: "All sources", value: "all" },
  { label: "Reddit", value: "reddit" },
  { label: "Hacker News", value: "hacker_news" },
  { label: "GitHub", value: "github" },
  { label: "Wikipedia", value: "wikipedia" },
] as const;

const SORT_OPTIONS = [
  { label: "Rank", value: "rank" },
  { label: "Score", value: "score" },
  { label: "Biggest mover", value: "mover" },
  { label: "Newest", value: "newest" },
] as const;

export function DashboardShell({ initialData }: DashboardShellProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [keyword, setKeyword] = useState("");
  const [selectedSource, setSelectedSource] = useState<string>("all");
  const [minimumScore, setMinimumScore] = useState<number | null>(0);
  const [sortBy, setSortBy] = useState<string>("rank");
  const [refreshError, setRefreshError] = useState<string | null>(null);
  const deferredKeyword = useDeferredValue(keyword);

  const filteredTrends = useMemo(() => {
    const normalizedKeyword = deferredKeyword.trim().toLowerCase();
    const minimum = minimumScore ?? 0;
    const trends = initialData.explorer.trends.filter((trend) => {
      const matchesSource =
        selectedSource === "all" || trend.sources.includes(selectedSource);
      const matchesKeyword =
        normalizedKeyword.length === 0 ||
        trend.name.toLowerCase().includes(normalizedKeyword) ||
        trend.evidencePreview.some((item) => item.toLowerCase().includes(normalizedKeyword));
      const matchesScore = trend.score.total >= minimum;
      return matchesSource && matchesKeyword && matchesScore;
    });

    return [...trends].sort((left, right) => {
      if (sortBy === "score") {
        return right.score.total - left.score.total || left.rank - right.rank;
      }
      if (sortBy === "mover") {
        return (right.rankChange ?? Number.NEGATIVE_INFINITY) - (left.rankChange ?? Number.NEGATIVE_INFINITY) || left.rank - right.rank;
      }
      if (sortBy === "newest") {
        return compareDates(right.firstSeenAt, left.firstSeenAt) || left.rank - right.rank;
      }
      return left.rank - right.rank;
    });
  }, [deferredKeyword, initialData.explorer.trends, minimumScore, selectedSource, sortBy]);

  function handleRefresh() {
    setRefreshError(null);
    startTransition(async () => {
      const response = await fetch("/api/refresh", { method: "POST" });
      if (!response.ok) {
        const payload = (await response.json()) as { error?: string };
        setRefreshError(payload.error ?? "Refresh failed");
        return;
      }
      router.refresh();
    });
  }

  return (
    <main className="dashboard-page">
      <section className="hero-panel">
        <div>
          <p className="eyebrow">Trend Friend</p>
          <h1>Trend explorer with movement, coverage, and score depth.</h1>
          <p className="hero-copy">
            The dashboard now reads a richer V2 export generated by the Python pipeline, so the
            browser can show rank movement and larger result sets without deriving business logic.
          </p>
        </div>
        <div className="hero-meta">
          <div className="stat-card">
            <span>Overview snapshot</span>
            <strong>{formatTimestamp(initialData.overview.generatedAt)}</strong>
          </div>
          <div className="stat-card">
            <span>Tracked trends</span>
            <strong>{initialData.overview.summary.trackedTrends}</strong>
          </div>
          <div className="stat-card">
            <span>Biggest mover</span>
            <strong>{initialData.overview.highlights.biggestMoverName ?? "No data"}</strong>
          </div>
          <div className="stat-card">
            <span>Total signals</span>
            <strong>{initialData.overview.summary.totalSignals}</strong>
          </div>
          <div className="stat-card">
            <span>Run health</span>
            <strong>{initialData.overview.operations.successRate.toFixed(1)}%</strong>
          </div>
          <Button className="refresh-button" disabled={isPending} onClick={handleRefresh}>
            {isPending ? "Refreshing..." : "Refresh trends"}
          </Button>
        </div>
      </section>

      <section className="overview-strip">
        <article className="overview-card">
          <span className="overview-label">Top trend</span>
          <strong>{initialData.overview.highlights.topTrendName ?? "No data"}</strong>
          <small>Highest ranked topic in the current snapshot.</small>
        </article>
        <article className="overview-card">
          <span className="overview-label">Newest trend</span>
          <strong>{initialData.overview.highlights.newestTrendName ?? "No data"}</strong>
          <small>Most recently first-seen topic in the ranked set.</small>
        </article>
        <article className="overview-card">
          <span className="overview-label">Pipeline health</span>
          <strong>{initialData.overview.operations.successRate.toFixed(1)}%</strong>
          <small>
            Average run {formatDuration(initialData.overview.operations.averageDurationMs)} across recent
            refreshes.
          </small>
        </article>
        <article className="overview-card">
          <span className="overview-label">Average score</span>
          <strong>{initialData.overview.summary.averageScore.toFixed(1)}</strong>
          <small>Mean total score across tracked trends.</small>
        </article>
      </section>

      <section className="filters-panel filters-panel-wide">
        <label className="filter-field">
          <span>Keyword</span>
          <Input
            className="text-input"
            placeholder="AI agents, robotics, battery..."
            value={keyword}
            onChange={(event) => setKeyword(event.target.value)}
          />
        </label>

        <label className="filter-field">
          <span>Source</span>
          <Select.Root value={selectedSource} onValueChange={(value) => setSelectedSource(value ?? "all")}>
            <Select.Trigger className="select-trigger">
              <Select.Value />
              <Select.Icon className="select-icon">+</Select.Icon>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner className="select-positioner" sideOffset={8}>
                <Select.Popup className="select-popup">
                  <Select.List className="select-list">
                    {SOURCE_FILTER_OPTIONS.map((option) => (
                      <Select.Item className="select-item" key={option.value} value={option.value}>
                        <Select.ItemText>{option.label}</Select.ItemText>
                      </Select.Item>
                    ))}
                  </Select.List>
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        </label>

        <label className="filter-field">
          <span>Sort</span>
          <Select.Root value={sortBy} onValueChange={(value) => setSortBy(value ?? "rank")}>
            <Select.Trigger className="select-trigger">
              <Select.Value />
              <Select.Icon className="select-icon">+</Select.Icon>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner className="select-positioner" sideOffset={8}>
                <Select.Popup className="select-popup">
                  <Select.List className="select-list">
                    {SORT_OPTIONS.map((option) => (
                      <Select.Item className="select-item" key={option.value} value={option.value}>
                        <Select.ItemText>{option.label}</Select.ItemText>
                      </Select.Item>
                    ))}
                  </Select.List>
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        </label>

        <label className="filter-field">
          <span>Minimum score</span>
          <NumberField.Root
            className="number-field"
            min={0}
            value={minimumScore}
            onValueChange={setMinimumScore}
          >
            <NumberField.Group className="number-group">
              <NumberField.Decrement className="number-button">-</NumberField.Decrement>
              <NumberField.Input className="number-input" />
              <NumberField.Increment className="number-button">+</NumberField.Increment>
            </NumberField.Group>
          </NumberField.Root>
        </label>
      </section>

      {refreshError ? <p className="error-banner">{refreshError}</p> : null}

      <section className="content-grid">
        <div className="ranking-panel">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Explorer</p>
              <h2>{filteredTrends.length} trends match the current filters</h2>
            </div>
          </div>

          {filteredTrends.length === 0 ? (
            <div className="empty-state">
              <h3>No trends match these filters.</h3>
              <p>Lower the minimum score or broaden the keyword and source filters.</p>
            </div>
          ) : (
            <div className="explorer-list">
              {filteredTrends.map((trend) => (
                <article className="explorer-card" key={trend.id}>
                  <div className="explorer-card-top">
                    <div className="trend-cell">
                      <strong>
                        <Link className="trend-link" href={`/trends/${trend.id}`}>
                          {trend.name}
                        </Link>
                      </strong>
                      <span className={trendStatusClassName(trend.status)}>
                        {formatTrendStatus(trend.status)}
                      </span>
                      <span>
                        First seen {trend.firstSeenAt ? formatDateOnly(trend.firstSeenAt) : "this run"}
                      </span>
                    </div>

                    <div className="explorer-metric">
                      <span>Rank</span>
                      <strong>#{trend.rank}</strong>
                    </div>

                    <div className="explorer-metric">
                      <span>Movement</span>
                      <strong className={movementClassName(trend.rankChange)}>
                        {formatRankChange(trend.rankChange)}
                      </strong>
                      <small>{formatMomentum(trend.momentum.percentDelta)}</small>
                    </div>

                    <div className="explorer-metric">
                      <span>Total</span>
                      <strong>{trend.score.total.toFixed(1)}</strong>
                      <small>
                        S {trend.score.social.toFixed(1)} / D {trend.score.developer.toFixed(1)} / K{" "}
                        {trend.score.knowledge.toFixed(1)}
                      </small>
                    </div>

                    <div className="explorer-metric">
                      <span>Signals</span>
                      <strong>{trend.coverage.signalCount}</strong>
                    </div>
                  </div>

                  <div className="source-row source-row-compact">
                    {trend.sources.map((source) => (
                      <span className="source-badge" key={source}>
                        {formatSourceLabel(source)}
                      </span>
                    ))}
                  </div>

                  <div className="evidence-preview evidence-preview-wide">
                    <strong>Evidence</strong>
                    <span>{trend.evidencePreview[0] ?? "No evidence available."}</span>
                  </div>
                </article>
              ))}
            </div>
          )}
        </div>

        <aside className="history-panel">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Operations</p>
              <h2>Recent pipeline runs</h2>
            </div>
          </div>

          <div className="snapshot-list">
            {initialData.overview.operations.recentRuns.map((run) => (
              <section className="snapshot-card" key={run.capturedAt}>
                <header>
                  <strong>{formatTimestamp(run.capturedAt)}</strong>
                  <span className={sourceHealthClassName(run.status)}>
                    {run.failedSourceCount === 0 ? "Healthy run" : "Degraded run"}
                  </span>
                </header>
                <p className="source-summary-copy">
                  {run.signalCount} signals, {run.rankedTrendCount} ranked trends,{" "}
                  {run.successfulSourceCount}/{run.sourceCount} sources healthy.
                </p>
                <p className="source-summary-copy">
                  Duration {formatDuration(run.durationMs)}.{" "}
                  {run.topTrendId && run.topTrendName ? (
                    <>
                      Top trend{" "}
                      <Link className="trend-link" href={`/trends/${run.topTrendId}`}>
                        {run.topTrendName}
                      </Link>
                      {run.topScore != null ? ` at ${run.topScore.toFixed(1)}.` : "."}
                    </>
                  ) : (
                    "No ranked top trend."
                  )}
                </p>
              </section>
            ))}
          </div>

          <div className="section-heading section-heading-spaced">
            <div>
              <p className="eyebrow">Source health</p>
              <h2>Contribution summary</h2>
            </div>
          </div>

          <div className="snapshot-list">
            {initialData.overview.sources.map((source) => (
              <section className="snapshot-card" key={source.source}>
                <header>
                  <strong>
                    <Link className="trend-link" href={`/sources/${source.source}`}>
                      {formatSourceLabel(source.source)}
                    </Link>
                  </strong>
                  <span className={sourceHealthClassName(source.status)}>
                    {formatSourceStatus(source.status)}
                  </span>
                </header>
                <p className="source-summary-copy">
                  {source.signalCount} signals across {source.trendCount} trends. Last fetch{" "}
                  {source.latestFetchAt ? formatTimestamp(source.latestFetchAt) : "not recorded"}.
                </p>
                <p className="source-summary-copy">
                  Last success {source.latestSuccessAt ? formatTimestamp(source.latestSuccessAt) : "never"}.
                  Latest item count {source.latestItemCount}. Duration {formatDuration(source.durationMs)}.
                </p>
                {source.usedFallback ? (
                  <p className="source-warning-copy">Latest successful fetch used fallback sample data.</p>
                ) : null}
                {source.errorMessage ? (
                  <p className="source-error-copy">{source.errorMessage}</p>
                ) : null}
              </section>
            ))}
          </div>
        </aside>
      </section>
    </main>
  );
}

function formatTimestamp(value: string) {
  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function formatDateOnly(value: string) {
  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
  }).format(new Date(value));
}

function formatSourceLabel(source: string) {
  return source
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function formatRankChange(value: number | null | undefined) {
  if (value == null) {
    return "New";
  }
  if (value > 0) {
    return `+${value}`;
  }
  if (value < 0) {
    return `${value}`;
  }
  return "0";
}

function formatMomentum(value: number | null | undefined) {
  if (value == null) {
    return "No prior run";
  }
  return `${value > 0 ? "+" : ""}${value.toFixed(1)}%`;
}

function movementClassName(rankChange: number | null | undefined) {
  if (rankChange == null) {
    return "movement-pill movement-pill-new";
  }
  if (rankChange > 0) {
    return "movement-pill movement-pill-up";
  }
  if (rankChange < 0) {
    return "movement-pill movement-pill-down";
  }
  return "movement-pill";
}

function compareDates(left: string | null, right: string | null) {
  if (left === null && right === null) {
    return 0;
  }
  if (left === null) {
    return -1;
  }
  if (right === null) {
    return 1;
  }
  return new Date(left).getTime() - new Date(right).getTime();
}

function formatSourceStatus(status: string) {
  if (status === "healthy") {
    return "Healthy";
  }
  if (status === "degraded") {
    return "Degraded";
  }
  return "Stale";
}

function sourceHealthClassName(status: string) {
  if (status === "healthy") {
    return "source-health-pill source-health-pill-healthy";
  }
  if (status === "degraded") {
    return "source-health-pill source-health-pill-degraded";
  }
  return "source-health-pill source-health-pill-stale";
}

function formatDuration(durationMs: number) {
  if (durationMs >= 1000) {
    return `${(durationMs / 1000).toFixed(1)}s`;
  }
  return `${durationMs}ms`;
}

function formatTrendStatus(status: string) {
  if (status === "breakout") {
    return "Breakout";
  }
  if (status === "rising") {
    return "Rising";
  }
  if (status === "cooling") {
    return "Cooling";
  }
  if (status === "new") {
    return "New";
  }
  return "Steady";
}

function trendStatusClassName(status: string) {
  if (status === "breakout") {
    return "trend-status-pill trend-status-pill-breakout";
  }
  if (status === "rising") {
    return "trend-status-pill trend-status-pill-rising";
  }
  if (status === "cooling") {
    return "trend-status-pill trend-status-pill-cooling";
  }
  if (status === "new") {
    return "trend-status-pill trend-status-pill-new";
  }
  return "trend-status-pill";
}
