import assert from "node:assert/strict";
import test from "node:test";

import { buildSourceImpactRows } from "@/lib/source-impact";
import type { DashboardOverviewSource, TrendDetailRecord, TrendExplorerRecord } from "@/lib/types";

const SOURCES: DashboardOverviewSource[] = [
  {
    source: "github",
    signalCount: 10,
    trendCount: 4,
    status: "healthy",
    latestFetchAt: "2026-03-12T12:00:00Z",
    latestSuccessAt: "2026-03-12T12:00:00Z",
    rawItemCount: 10,
    latestItemCount: 10,
    keptItemCount: 10,
    yieldRatePercent: 100,
    durationMs: 120,
    rawTopicCount: 10,
    mergedTopicCount: 10,
    duplicateTopicCount: 0,
    duplicateTopicRate: 0,
    usedFallback: false,
    errorMessage: null,
  },
  {
    source: "polymarket",
    signalCount: 3,
    trendCount: 2,
    status: "healthy",
    latestFetchAt: "2026-03-12T12:00:00Z",
    latestSuccessAt: "2026-03-12T12:00:00Z",
    rawItemCount: 3,
    latestItemCount: 3,
    keptItemCount: 3,
    yieldRatePercent: 100,
    durationMs: 110,
    rawTopicCount: 3,
    mergedTopicCount: 3,
    duplicateTopicCount: 0,
    duplicateTopicRate: 0,
    usedFallback: false,
    errorMessage: null,
  },
  {
    source: "reddit",
    signalCount: 8,
    trendCount: 4,
    status: "healthy",
    latestFetchAt: "2026-03-12T12:00:00Z",
    latestSuccessAt: "2026-03-12T12:00:00Z",
    rawItemCount: 8,
    latestItemCount: 8,
    keptItemCount: 8,
    yieldRatePercent: 100,
    durationMs: 130,
    rawTopicCount: 8,
    mergedTopicCount: 8,
    duplicateTopicCount: 0,
    duplicateTopicRate: 0,
    usedFallback: false,
    errorMessage: null,
  },
];

const TRENDS: TrendExplorerRecord[] = [
  {
    id: "ai-agents",
    name: "AI Agents",
    category: "ai-machine-learning",
    status: "rising",
    volatility: "stable",
    rank: 1,
    previousRank: null,
    rankChange: null,
    firstSeenAt: null,
    latestSignalAt: "2026-03-12T12:00:00Z",
    score: { total: 50, social: 20, developer: 20, knowledge: 0, search: 5, advertising: 0, diversity: 5 },
    momentum: { previousRank: null, rankChange: null, absoluteDelta: null, percentDelta: null },
    coverage: { sourceCount: 2, signalCount: 10 },
    sources: ["github", "reddit"],
    evidencePreview: [],
    audienceSummary: [],
    primaryEvidence: null,
    recentHistory: [],
    seasonality: null,
  },
  {
    id: "bitcoin",
    name: "Bitcoin",
    category: "crypto",
    status: "rising",
    volatility: "volatile",
    rank: 2,
    previousRank: null,
    rankChange: null,
    firstSeenAt: null,
    latestSignalAt: "2026-03-12T12:00:00Z",
    score: { total: 40, social: 10, developer: 0, knowledge: 0, search: 25, advertising: 0, diversity: 5 },
    momentum: { previousRank: null, rankChange: null, absoluteDelta: null, percentDelta: null },
    coverage: { sourceCount: 2, signalCount: 8 },
    sources: ["polymarket", "reddit"],
    evidencePreview: [],
    audienceSummary: [],
    primaryEvidence: null,
    recentHistory: [],
    seasonality: null,
  },
];

const DETAILS = new Map<string, TrendDetailRecord>([
  [
    "ai-agents",
    {
      id: "ai-agents",
      name: "AI Agents",
      category: "ai-machine-learning",
      status: "rising",
      volatility: "stable",
      rank: 1,
      previousRank: null,
      rankChange: null,
      firstSeenAt: null,
      latestSignalAt: "2026-03-12T12:00:00Z",
      score: { total: 50, social: 20, developer: 20, knowledge: 0, search: 5, advertising: 0, diversity: 5 },
      momentum: { previousRank: null, rankChange: null, absoluteDelta: null, percentDelta: null },
      breakoutPrediction: { confidence: 0, predictedDirection: "flat", signals: [] },
      forecast: null,
      opportunity: { composite: 0, discovery: 0, seo: 0, content: 0, product: 0, investment: 0, reasoning: [] },
      coverage: { sourceCount: 2, signalCount: 10 },
      sources: ["github", "reddit"],
      history: [],
      sourceBreakdown: [],
      sourceContributions: [
        {
          source: "github",
          signalCount: 5,
          latestSignalAt: "2026-03-12T12:00:00Z",
          estimatedScore: 28,
          scoreSharePercent: 56,
          score: { total: 28, social: 0, developer: 24, knowledge: 0, search: 2, advertising: 0, diversity: 2 },
        },
        {
          source: "reddit",
          signalCount: 5,
          latestSignalAt: "2026-03-12T12:00:00Z",
          estimatedScore: 12,
          scoreSharePercent: 24,
          score: { total: 12, social: 10, developer: 0, knowledge: 0, search: 1, advertising: 0, diversity: 1 },
        },
      ],
      geoSummary: [],
      audienceSummary: [],
      evidenceItems: [],
      primaryEvidence: null,
      relatedTrends: [],
      seasonality: null,
    },
  ],
  [
    "bitcoin",
    {
      id: "bitcoin",
      name: "Bitcoin",
      category: "crypto",
      status: "rising",
      volatility: "volatile",
      rank: 2,
      previousRank: null,
      rankChange: null,
      firstSeenAt: null,
      latestSignalAt: "2026-03-12T12:00:00Z",
      score: { total: 40, social: 10, developer: 0, knowledge: 0, search: 25, advertising: 0, diversity: 5 },
      momentum: { previousRank: null, rankChange: null, absoluteDelta: null, percentDelta: null },
      breakoutPrediction: { confidence: 0, predictedDirection: "flat", signals: [] },
      forecast: null,
      opportunity: { composite: 0, discovery: 0, seo: 0, content: 0, product: 0, investment: 0, reasoning: [] },
      coverage: { sourceCount: 2, signalCount: 8 },
      sources: ["polymarket", "reddit"],
      history: [],
      sourceBreakdown: [],
      sourceContributions: [
        {
          source: "polymarket",
          signalCount: 3,
          latestSignalAt: "2026-03-12T12:00:00Z",
          estimatedScore: 18,
          scoreSharePercent: 45,
          score: { total: 18, social: 0, developer: 0, knowledge: 0, search: 16, advertising: 0, diversity: 2 },
        },
        {
          source: "reddit",
          signalCount: 5,
          latestSignalAt: "2026-03-12T12:00:00Z",
          estimatedScore: 3,
          scoreSharePercent: 7.5,
          score: { total: 3, social: 3, developer: 0, knowledge: 0, search: 0, advertising: 0, diversity: 0 },
        },
      ],
      geoSummary: [],
      audienceSummary: [],
      evidenceItems: [],
      primaryEvidence: null,
      relatedTrends: [],
      seasonality: null,
    },
  ],
]);

test("buildSourceImpactRows counts material and supporting source influence across published trends", () => {
  const rows = buildSourceImpactRows(SOURCES, TRENDS, DETAILS);

  assert.deepEqual(
    rows.slice(0, 3).map((row) => ({
      source: row.source,
      material: row.materialTrendCount,
      total: row.totalTrendCount,
      average: Number(row.averageMaterialSharePercent.toFixed(1)),
      examples: row.exampleTrendNames,
    })),
    [
      { source: "reddit", material: 1, total: 2, average: 24, examples: ["AI Agents"] },
      { source: "github", material: 1, total: 1, average: 56, examples: ["AI Agents"] },
      { source: "polymarket", material: 1, total: 1, average: 45, examples: ["Bitcoin"] },
    ],
  );
});
